config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls', namespace='users')),
    path('', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__', include(debug_toolbar.urls)),]

django/core/urls.py
from django.urls import path

from . import views


app_name = 'core'
urlpatterns = [
    path('movies/', views.MovieList.as_view(), name='MovieList'),
    path('movies/top/', views.TopMovies.as_view(), name='TopMovies'),
    path('movie/<int:pk>/', views.MovieDetail.as_view(), name='MovieDetail'),
    path('person/<int:pk>/', views.PersonDetailView.as_view(), name='PersonDetail'),
    path('movie/<int:movie_id>/vote/', views.CreateVote.as_view(), name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>/', views.UpdateVote.as_view(),
         name='UpdateVote'),
]

core/models.py
from django.db import models
from django.conf import settings
from django.db.models.aggregates import Sum


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            'directed',
            'writing_credits',
            'role_set__movie')


class MovieManager(models.Manager):
    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related(
            'director')
        qs = qs.prefetch_related(
            'writers', 'actors')
        return qs

    def all_with_related_persons_and_scores(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum('vote__value'))
        return qs

    def top_movies(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(vote__sum=Sum('vote__value'))
        qs = qs.exclude(vote__sum=None)
        qs = qs.order_by('-vote__sum')
        qs = qs[:limit]
        return qs


class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140, blank=True, null=True)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    objects = PersonManager()

    class Meta:
        ordering = ('first_name', 'last_name')

    def __str__(self):
        if not self.first_name:
            self.first_name = ''
        if not self.last_name:
            self.last_name = ''
        if self.died:
            return '{} {} ({}-{})'.format(
                self.first_name, self.last_name, self.born, self.died)
        return '{} {} ({})'.format(self.first_name, self.last_name, self.born)

    def is_actor(self):
        pass

    def is_writer(self):
        pass

    def is_director(self):
        pass


class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audience'),
        (RATED_PG, 'PG - Parental Guidance'),
        (RATED_R, 'R - Restricted'),)

    title = models.CharField(max_length=140)
    plot = models.TextField()
    poster = models.ImageField(
        upload_to='movie_posters',
        default='default-movie.png',
        blank=True)
    director = models.ForeignKey(
        to='Person',
        on_delete=models.SET_NULL,
        related_name='directed',
        null=True,
        blank=True)
    writers = models.ManyToManyField(
        to='Person',
        related_name='writing_credits',
        blank=True)
    actors = models.ManyToManyField(
        to='Person',
        through='Role',
        related_name='acting_credits',
        blank=True)
    year = models.PositiveIntegerField()
    rating = models.IntegerField(
        choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveIntegerField()

    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return '{} {} {}'.format(
            self.movie_id, self.person_id, self.name
        )

    class Meta:
        unique_together = ('movie', 'person', 'name')


class VoteManager(models.Manager):

    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(
                movie=movie,
                user=user
            )
        except Vote.DoesNotExist:
            return Vote(
                movie=movie,
                user=user
            )


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, '👍'),
        (DOWN, '👎')
    )

    value = models.SmallIntegerField(choices=VALUE_CHOICES, )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)

    objects = VoteManager()

    class Meta:
        unique_together = ('user', 'movie')

django/core/models.py
from django.db import models
from django.conf import settings
from django.db.models.aggregates import Sum


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            'directed',
            'writing_credits',
            'role_set__movie')


class MovieManager(models.Manager):
    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related(
            'director')
        qs = qs.prefetch_related(
            'writers', 'actors')
        return qs

    def all_with_related_persons_and_scores(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum('vote__value'))
        return qs

    def top_movies(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(vote__sum=Sum('vote__value'))
        qs = qs.exclude(vote__sum=None)
        qs = qs.order_by('-vote__sum')
        qs = qs[:limit]
        return qs


class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140, blank=True, null=True)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    objects = PersonManager()

    class Meta:
        ordering = ('first_name', 'last_name')

    def __str__(self):
        if not self.first_name:
            self.first_name = ''
        if not self.last_name:
            self.last_name = ''
        if self.died:
            return '{} {} ({}-{})'.format(
                self.first_name, self.last_name, self.born, self.died)
        return '{} {} ({})'.format(self.first_name, self.last_name, self.born)

    def is_actor(self):
        pass

    def is_writer(self):
        pass

    def is_director(self):
        pass


class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audience'),
        (RATED_PG, 'PG - Parental Guidance'),
        (RATED_R, 'R - Restricted'),)

    title = models.CharField(max_length=140)
    plot = models.TextField()
    poster = models.ImageField(
        upload_to='movie_posters',
        default='default-movie.png',
        blank=True)
    director = models.ForeignKey(
        to='Person',
        on_delete=models.SET_NULL,
        related_name='directed',
        null=True,
        blank=True)
    writers = models.ManyToManyField(
        to='Person',
        related_name='writing_credits',
        blank=True)
    actors = models.ManyToManyField(
        to='Person',
        through='Role',
        related_name='acting_credits',
        blank=True)
    year = models.PositiveIntegerField()
    rating = models.IntegerField(
        choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveIntegerField()

    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return '{} {} {}'.format(
            self.movie_id, self.person_id, self.name
        )

    class Meta:
        unique_together = ('movie', 'person', 'name')


class VoteManager(models.Manager):

    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(
                movie=movie,
                user=user
            )
        except Vote.DoesNotExist:
            return Vote(
                movie=movie,
                user=user
            )


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, '👍'),
        (DOWN, '👎')
    )

    value = models.SmallIntegerField(choices=VALUE_CHOICES, )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)

    objects = VoteManager()

    def __str__(self):
        vote = 'Upvote' if self.value == 1 else 'Downvote'
        return f"{self.user} {vote}d {self.movie}"

    class Meta:
        unique_together = ('user', 'movie')

django/core/forms.py
from django import forms
from django.contrib.auth import get_user_model

from core.models import Vote, Movie


class VoteForm(forms.ModelForm):

    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True,
    )
    value = forms.ChoiceField(
        label='Vote',
        widget=forms.RadioSelect,
        choices=Vote.VALUE_CHOICES,
    )

    class Meta:
        model = Vote
        fields = ('value', 'user', 'movie',)

django/core/views.py
import django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView)

from core.models import Movie, Person, Vote
from core.forms import VoteForm
from core.mixins import CachePageVaryOnCoockieMixin


class MovieList(CachePageVaryOnCoockieMixin, ListView):
    model = Movie
    paginate_by = 12

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super().get_context_data(**kwargs)
        top_movies = Movie.objects.top_movies()
        ctx['top_movies'] = top_movies
        return ctx


class MovieDetail(DetailView):
    queryset = Movie.objects.all_with_related_persons_and_scores()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object,
                user=self.request.user)
            if vote.id:
                vote_form_url = reverse(
                    'core:UpdateVote',
                    kwargs={'movie_id': vote.movie.id, 'pk': vote.id})
            else:
                vote_form_url = (
                    reverse(
                        'core:CreateVote',
                        kwargs={'movie_id': self.object.id}))
            vote_form = VoteForm(instance=vote)
            ctx['vote_form'] = vote_form
            ctx['vote_form_url'] = vote_form_url
        return ctx


class PersonDetailView(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id}
        )
        return redirect(to=movie_detail_url)


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(
            queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied(
                'cannot change another users vote.'
            )
        return vote

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id}
        )

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id}
        )
        return redirect(to=movie_detail_url)


class TopMovies(ListView):
    template_name = 'core/top_movies_list.html'

    def get_queryset(self):
        limit = 10
        key = 'top_movies_%s' % limit
        cached_qs = cache.get(key)
        if cached_qs:
            same_django = cached_qs._django_version == django.get_version()
            if same_django:
                return cached_qs
        qs = Movie.objects.top_movies(
            limit=limit,)
        cache.set(key, qs)
        return qs

django/core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %} {{ object.title }} - {{ block.super }} {% endblock %}

{% block main %}

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <h2>{{ object }}</h2>
        <ul>

        </ul>
          <p class="lead">
              {{ object.plot }}
          </p>
      </div>
    </div>
  </div>
</div>

<div class="card p-3 mt-3">
  <h5><b>Director:</b> {{ object.director }}</h5>
  <h5><b>Writer(s):</b></h5>
    <ul>
     {% for writer in object.writers.all %}
     <li>{{ writer.first_name }}</li>
     {% endfor %}
    </ul>
</div>

<div class="card mt-3">
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Actor</th>
          <th scope="col">Role</th>
        </tr>
      </thead>
      <tbody>
      {% for actor in object.actors.all %}
        <tr>
          <td>{{ actor }}</td>
          <td>{{ actor.role_set.all.first.name }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}


{% block sidebar %}
<div>
  <h3>Rating:
    <span class="badge badge-primary">{{ object.get_rating_display }}</span>
  </h3>
</div>

<div class="vote">
  {% if vote_form %}
  <form action="{{ vote_form_url }}" method="post">
    {% csrf_token %}
    <div class="btns d-inline">
      {{ vote_form.as_p }}
    </div>
    <input type="submit" value="Vote" class="btn btn-primary">
  </form>
  <h4 class="mt-3">Total Vote(s):
    <span class="badge badge-primary">{{ object.score }}</span>
  </h4>

  {% else %}
  <p>Log in to vote for this movie.</p>
  {% endif %}
</div>
{% endblock %}


{% block javascript %}
<script>

</script>
{% endblock %}

django/core/templates/core/movie_list.html
{% extends 'base.html' %}
{% load cache %}

{% block title %} All Movies - {{ block.super }} {% endblock %}

{% block main %}
<div class="row justify-content-center">
{% for movie in object_list %}
<div class="col-md-3">
  <a href="{% url 'core:MovieDetail' pk=movie.id %}" class="d-block">
    <div class="card my-1">
      <div class="text-dark text-center">
        {{ movie.get_rating_display }}
      </div>
      <div class="card-body"
           style="background: url('{{ movie.poster }}'); min-height: 350px;
            background-size: 100% 100%;">
      </div>
      <div class="info text-center">
        <p class="card-title small">{{ movie }}</p>
        <a href="{% url 'core:MovieDetail' pk=movie.id %}" class="small">View More</a>
      </div>
    </div>
  </a>
</div>
{% empty %}
   <h3> No Movies Yet.</h3>
{% endfor %}
</div>


{% if is_paginated %}
<nav aria-label="Page navigation example" class="table-responsive mb-2">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    {% endif %}

    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

{% endblock %}


{% block sidebar %}

<div class="row">
  <ul class="list-group">
    <li class="list-group-item active">TOP 10 MOVIES</li>
    {% cache 300 top10 %}
    {% for movie in top_movies %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <a href="{% url 'core:MovieDetail' pk=movie.id %}">
        {{ movie.title }}
      </a>
      <span class="badge badge-primary">
          {{ movie.vote__sum }}
      </span>
    </li>
    {% empty %}
      <li class="list-group-item">Vote movies to make them top.</li>
    {% endfor %}
    {% endcache %}
  </ul>
</div>

{% endblock %}

django/core/templates/core/person_detail.html
{% extends 'base.html' %}

{% block title %} {{ object.first_name }} - {{ block.super }} {% endblock %}

{% block main %}

<div class="row border mb-2">
  <div class="col-md-12">
    <h3>{{ object.first_name }} {% if object.last_name %}{{ object.last_name }}{% endif %}</h3>
    <a href="" class="small">Actor</a>
    <a href="" class="small">Producer</a>
    <a href="" class="small">Writer</a>

    <div class="info">
      <b>Born:</b> {{ object.born }}
      {% if died %}
      <b>Died:</b> {{ object.died }}
      {% endif %}
    </div>
  </div>
</div>

<div class="row border">
  <div class="col-md-12">
    <h3>Filmography</h3>
    <h4 class="text-success">Actor:</h4>
    {% for role in object.role_set.all %}
      <li>
        <a href="{% url 'core:MovieDetail' pk=movie.id %}">{{ role.movie }}: </a> {{ role.name }}
      </li>
    {% endfor %}

    <h4 class="text-success">Director:</h4>
    {% for movie in object.directed.all %}
      <li>
        <a href="{% url 'core:MovieDetail' pk=movie.id %}">{{ movie }}: </a>
      </li>
    {% endfor %}

    <h4 class="text-success">Writer:</h4>
    {% for role in object.writing_credits.all %}
      <li>
        <a href="{% url 'core:MovieDetail' pk=movie.id %}">{{ movie }}: </a>
      </li>
    {% endfor %}
  </div>

</div>

{% endblock %}

django/core/templates/core/top_movies_list.html
{% extends 'base.html' %}

{% block title %} Top 10 Movies - {{ block.super }} {% endblock %}

{% block main %}

<h2>Top 10 Movies</h2>
<small>Top 10 movies that moviegeeks loved.</small>

<table class="table border">
  <thead>
    <tr>
      <th scope="col">Rank and Title</th>
      <th scope="col">MovieGeek Rating</th>
      <th scope="col">Your Vote</th>
    </tr>
  </thead>
  <tbody>
    {% for movie in object_list %}
    <tr>
      <td scope="row">
        {{ forloop.counter }}
        <a href="{% url 'core:MovieDetail' pk=movie.id %}">
          {{ movie }}
        </a>
      </td>
      <td>{{ movie.get_rating_display }}</td>
      <td></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}