config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls', namespace='users')),
    path('', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__', include(debug_toolbar.urls)),]

django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import common_settings as cs
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls', namespace='users')),
    path('', include('core.urls', namespace='core')),
] + static(cs.MEDIA_URL, document_root=cs.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__', include(debug_toolbar.urls)),]

django/core/urls.py
from django.urls import path

from . import views


app_name = 'core'
urlpatterns = [
    path('movies/', views.MovieList.as_view(), name='MovieList'),
    path('movies/top/', views.TopMovies.as_view(), name='TopMovies'),
    path('movie/<int:pk>/', views.MovieDetail.as_view(), name='MovieDetail'),
    path('person/<int:pk>/', views.PersonDetailView.as_view(), name='PersonDetail'),
    path('movie/<int:movie_id>/vote/', views.CreateVote.as_view(), name='CreateVote'),
    path('movie/<int:movie_id>/vote/<int:pk>/', views.UpdateVote.as_view(),
         name='UpdateVote'),
]

django/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'users'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

django/core/models.py
from django.db import models
from django.conf import settings
from django.db.models.aggregates import Sum


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            'directed',
            'writing_credits',
            'role_set__movie')


class MovieManager(models.Manager):
    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related(
            'director')
        qs = qs.prefetch_related(
            'writers', 'actors')
        return qs

    def all_with_related_persons_and_scores(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum('vote__value'))
        return qs

    def top_movies(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(vote__sum=Sum('vote__value'))
        qs = qs.exclude(vote__sum=None)
        qs = qs.order_by('-vote__sum')
        qs = qs[:limit]
        return qs


class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140, blank=True, null=True)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    objects = PersonManager()

    class Meta:
        ordering = ('first_name', 'last_name')

    def __str__(self):
        if not self.first_name:
            self.first_name = ''
        if not self.last_name:
            self.last_name = ''
        if self.died:
            return '{} {} ({}-{})'.format(
                self.first_name, self.last_name, self.born, self.died)
        return '{} {} ({})'.format(self.first_name, self.last_name, self.born)

    def is_actor(self):
        pass

    def is_writer(self):
        pass

    def is_director(self):
        pass


class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audience'),
        (RATED_PG, 'PG - Parental Guidance'),
        (RATED_R, 'R - Restricted'),)

    title = models.CharField(max_length=140)
    plot = models.TextField()
    poster = models.ImageField(
        upload_to='movie_posters',
        default='default-movie.png',
        blank=True)
    director = models.ForeignKey(
        to='Person',
        on_delete=models.SET_NULL,
        related_name='directed',
        null=True,
        blank=True)
    writers = models.ManyToManyField(
        to='Person',
        related_name='writing_credits',
        blank=True)
    actors = models.ManyToManyField(
        to='Person',
        through='Role',
        related_name='acting_credits',
        blank=True)
    year = models.PositiveIntegerField()
    rating = models.IntegerField(
        choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveIntegerField()

    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return '{} {} {}'.format(
            self.movie_id, self.person_id, self.name
        )

    class Meta:
        unique_together = ('movie', 'person', 'name')


class VoteManager(models.Manager):

    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(
                movie=movie,
                user=user
            )
        except Vote.DoesNotExist:
            return Vote(
                movie=movie,
                user=user
            )


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, '👍'),
        (DOWN, '👎')
    )

    value = models.SmallIntegerField(choices=VALUE_CHOICES, )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)

    objects = VoteManager()

    def __str__(self):
        vote = 'Upvote' if self.value == 1 else 'Downvote'
        return f"{self.user} {vote}d {self.movie}"

    class Meta:
        unique_together = ('user', 'movie')

django/users/models.py
from django.db import models

# Create your models here.

django/core/forms.py
from django import forms
from django.contrib.auth import get_user_model

from core.models import Vote, Movie


class VoteForm(forms.ModelForm):

    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True,
    )
    value = forms.ChoiceField(
        label='Vote',
        widget=forms.RadioSelect,
        choices=Vote.VALUE_CHOICES,
    )

    class Meta:
        model = Vote
        fields = ('value', 'user', 'movie',)

django/core/views.py
import django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView)

from core.models import Movie, Person, Vote
from core.forms import VoteForm
from core.mixins import CachePageVaryOnCoockieMixin


class MovieList(CachePageVaryOnCoockieMixin, ListView):
    model = Movie
    paginate_by = 12

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super().get_context_data(**kwargs)
        top_movies = Movie.objects.top_movies()
        ctx['top_movies'] = top_movies
        return ctx


class MovieDetail(DetailView):
    queryset = Movie.objects.all_with_related_persons_and_scores()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object,
                user=self.request.user)
            if vote.id:
                vote_form_url = reverse(
                    'core:UpdateVote',
                    kwargs={'movie_id': vote.movie.id, 'pk': vote.id})
            else:
                vote_form_url = (
                    reverse(
                        'core:CreateVote',
                        kwargs={'movie_id': self.object.id}))
            vote_form = VoteForm(instance=vote)
            ctx['vote_form'] = vote_form
            ctx['vote_form_url'] = vote_form_url
        return ctx


class PersonDetailView(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id}
        )
        return redirect(to=movie_detail_url)


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(
            queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied(
                'cannot change another users vote.'
            )
        return vote

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id}
        )

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={'pk': movie_id}
        )
        return redirect(to=movie_detail_url)


class TopMovies(ListView):
    template_name = 'core/top_movies_list.html'

    def get_queryset(self):
        limit = 10
        key = 'top_movies_%s' % limit
        cached_qs = cache.get(key)
        if cached_qs:
            same_django = cached_qs._django_version == django.get_version()
            if same_django:
                return cached_qs
        qs = Movie.objects.top_movies(
            limit=limit,)
        cache.set(key, qs)
        return qs

django/users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class RegisterView(CreateView):
    template_name = 'users/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('core:MovieList')

django/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title> {% block title %} MovieGeek {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
      <style>
          #navbarNav ul li a.active{color: red}
          a:hover { text-decoration: none }
          .btns.d-inline #id_value { list-style: none; padding-left: 0; }
          .btns.d-inline #id_value li { display: inline; }
      </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">MovieGeek</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:MovieList' %}">Movies</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'core:TopMovies' %}">Top 10</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link disabled" href="">{{ request.user.username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    
    
    <div class="container-fluid p-5">
        <div class="row">
            <div class="col-md-8">
                {% block main %} {% endblock %}
            </div>
            <div class="col-md-4">
                {% block sidebar %} {% endblock %}
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script type="text/javascript">
      var loc = window.location.pathname;

       $('#navbarNav').find('a').each(function() {
         $(this).toggleClass('active', $(this).attr('href') == loc);
      });
    </script>

  {% block javascript %}
  {% endblock %}
  </body>
</html>